# django-core-utils-test travis config file
# TODO: change email address

sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.6.2

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose -f docker-compose-sqlite.yml up --abort-on-container-exit


#language: python
#
#
#sudo: false
#
#python: '2.7'
#
#env:
#  - TOX_ENV=py27-django18
#  - TOX_ENV=py27-django19
#
#matrix:
#  fast_finish: true
#  include:
#    - python: '3.5'
#      env: TOX_ENV=py35-django19
#    - python: '3.5'
#      env: TOX_ENV=py35-django18
#
#       
#install:
#  - pip install tox
#
#script:
#  - tox -e $TOX_ENV

notifications:
  email:
    recipients:
      - amnon.janiv@ondalear.com

    on_success: change
    on_failure: always
  
branches:
  only:
    - master
    - develop