# docker-compose posgtres configuration file
version: "3"
services:
  db-postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5433:5432"
  web-test:
    build: 
      context: .
      dockerfile: docker-dockerfile-postgres.yml
    command: ./docker_run_tests.sh -w 3 -t postgres -d db-postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db-postgres
    env_file: 
      - docker_env/common
      - docker_env/postgres
